### ISSUE TITLE
Add python 3 support and Travis tests

### ISSUE THREAD

**Issue by winhamwr** [PolicyStat/terrarium#8]
It's very possible that terrarium already works with python 3, but it needs to be tested and confirmed.

**Comment by nicoulaj** [comment]
It doesn't:
```
Traceback (most recent call last):
   File ".env/bin/terrarium", line 7, in <module>
     from terrarium.terrarium import main
   File ".env/lib64/python3.6/site-packages/terrarium/terrarium.py", line 88
     except OSError, why:
```

**Comment by maroux** [comment]
There's some work already done on this: https://github.com/PolicyStat/terrarium/pull/64
